//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 colors.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 0 files.
  struct file {
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 7 images.
  struct image {
    /// Image `gray`.
    static let gray = Rswift.ImageResource(bundle: R.hostingBundle, name: "gray")
    /// Image `green`.
    static let green = Rswift.ImageResource(bundle: R.hostingBundle, name: "green")
    /// Image `orange`.
    static let orange = Rswift.ImageResource(bundle: R.hostingBundle, name: "orange")
    /// Image `purple`.
    static let purple = Rswift.ImageResource(bundle: R.hostingBundle, name: "purple")
    /// Image `red`.
    static let red = Rswift.ImageResource(bundle: R.hostingBundle, name: "red")
    /// Image `sky`.
    static let sky = Rswift.ImageResource(bundle: R.hostingBundle, name: "sky")
    /// Image `white`.
    static let white = Rswift.ImageResource(bundle: R.hostingBundle, name: "white")
    
    /// `UIImage(named: "gray", bundle: ..., traitCollection: ...)`
    static func gray(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.gray, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "green", bundle: ..., traitCollection: ...)`
    static func green(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.green, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "orange", bundle: ..., traitCollection: ...)`
    static func orange(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.orange, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "purple", bundle: ..., traitCollection: ...)`
    static func purple(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.purple, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "red", bundle: ..., traitCollection: ...)`
    static func red(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.red, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "sky", bundle: ..., traitCollection: ...)`
    static func sky(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.sky, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "white", bundle: ..., traitCollection: ...)`
    static func white(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.white, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 2 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `ColorCollectionViewCell`.
    static let colorCollectionViewCell: Rswift.ReuseIdentifier<ColorCollectionViewCell> = Rswift.ReuseIdentifier(identifier: "ColorCollectionViewCell")
    /// Reuse identifier `SchedulerTableCell`.
    static let schedulerTableCell: Rswift.ReuseIdentifier<SchedulerTableViewCell> = Rswift.ReuseIdentifier(identifier: "SchedulerTableCell")
    
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 3 storyboards.
  struct storyboard {
    /// Storyboard `Home`.
    static let home = _R.storyboard.home()
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Start`.
    static let start = _R.storyboard.start()
    
    /// `UIStoryboard(name: "Home", bundle: ...)`
    static func home(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.home)
    }
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Start", bundle: ...)`
    static func start(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.start)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try start.validate()
      try home.validate()
    }
    
    struct home: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = HomeViewController
      
      let bundle = R.hostingBundle
      let homeViewController = StoryboardViewControllerResource<HomeViewController>(identifier: "HomeViewController")
      let name = "Home"
      
      func homeViewController(_: Void = ()) -> HomeViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: homeViewController)
      }
      
      static func validate() throws {
        if _R.storyboard.home().homeViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'homeViewController' could not be loaded from storyboard 'Home' as 'HomeViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    struct start: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "Start"
      let startSettingViewController = StoryboardViewControllerResource<StartSettingViewController>(identifier: "StartSettingViewController")
      
      func startSettingViewController(_: Void = ()) -> StartSettingViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: startSettingViewController)
      }
      
      static func validate() throws {
        if _R.storyboard.start().startSettingViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'startSettingViewController' could not be loaded from storyboard 'Start' as 'StartSettingViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
